---

all:
  hosts:
    server1:
      ansible_host: 172.31.77.16
      ansible_user: ubuntu
      key_file: /home/ubuntu/.ssh/id_rsa.pub

  children:
    angular_servers:
      hosts:
        server1: {}
    
    podman_nodes:
      children:
        angular_servers:


        
