---

all:
  hosts:
    server1:
      ansible_host: 172.31.77.16
      ansible_user: flisol-admin
      key_file: /home/flisol-admin/.ssh/id_rsa.pub

  children:
    angular_servers:
      hosts:
        server1: {}
    
    podman_nodes:
      children:
        angular_servers:


        
