---

all:
  hosts:
    server1:
      ansible_host: 11.0.0.141
      ansible_user: kubernetes
      key_file: /home/carlos_xpk_2bc/.ssh/id_ed25519

  children:
    angular_servers:
      hosts:
        server1: {}
    
    podman_nodes:
      children:
        angular_servers:


        