---
- name: Obtener r del contenedor
  containers.podman.podman_container_info:
    name: "{{ contenedor_nombre }}"
  register: informacion_contenedor

- name: Crear la variable para la IP del contenedor
  set_fact:
    red_servicio_puerto_contenedor: "{{ informacion_contenedor.containers[0].NetworkSettings.Ports[red_servicio_puerto_protocolo][0].HostPort }}"
  
- name: Crear archivo de configuracion NGINX
  template:
    src: templates/nginx.j2
    dest: "/etc/nginx/conf.d/{{ app_name }}.conf"

- name: Reiniciar nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted