- name: Creacion de red
  containers.podman.podman_network:
    name: "{{ red_servicio_nombre }}"
    subnet: "{{ red_servicio_subnet }}"

- name: Crear contenedor de la aplicacion
  containers.podman.podman_container:
    name: "{{ contenedor_nombre }}"
    image: "localhost/{{ app_name }}:latest"
    state: started
    recreate: true
    network: "{{ red_servicio_nombre }}"
    publish_all: true

