---
- name: Pull de la imagen base
  containers.podman.podman_image:
    name: docker.io/library/node
    tag: 18-alpine


- name: Crear imagen del contenedor
  containers.podman.podman_image:
    name: "{{ app_name }}"
    tag: "latest"
    path: "{{ ruta_directorio }}"
    build:
      cache: false
      force_rm: true