---

- name: Pull de la imagen base
  containers.podman.podman_image:
    name: docker.io/library/node
    tag: 18-alpine

- name: Generar hash
  shell: openssl rand -hex 8
  register: hash_imagen

- name: Crear imagen del contenedor para pruebas
  containers.podman.podman_image:
    name: "{{ app_name }}-test"
    tag: "{{ hash_imagen.stdout }}"
    path: "{{ ruta_directorio }}"
    build:
      cache: false
      force_rm: true

- name: Crear el contenedor de pruebas
  containers.podman.podman_container:
    name: "{{ contenedor_nombre }}-{{ hash_imagen.stdout }}"
    image: "localhost/{{ app_name }}-test:{{ hash_imagen.stdout }}"
    state: started
    recreate: true
    #network: "{{ red_servicio_nombre }}"
    publish_all: true

- name: Prueba check de salud del contenedor
  shell: "podman exec {{ contenedor_nombre }}-{{ hash_imagen.stdout }} sh -c 'sleep 15 ; curl 127.0.0.1:4200'"
  ignore_errors: true
  register: check_curl
  retries: 5
  delay: 10
