# {{ ansible_managed }}
FROM node:18-alpine
ENV NG_CLI_ANALYTICS=false
RUN apk add curl

COPY . /src/app
WORKDIR /src/app
EXPOSE {{ contenedor_puerto }}
RUN npm install
RUN npm install -g @angular/cli@latest
CMD ng serve --host=0.0.0.0 --disable-host-check

